import logging

from quorum_eth_py import RumEthChainContract

""" the abi file is generated by remix when contract published"""
from temp.mint_nft.abi_devclub import abi as abi_devclub

logging.basicConfig(
    level=logging.DEBUG, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)


class DEVCLUB:
    PVTKEY = "0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    CONTRACT_ADDRESS = "0x2317B756bA89E87A7AACf63007b2e57A6a60D57a"
    ABI = abi_devclub


devclub = RumEthChainContract(DEVCLUB.ABI, DEVCLUB.CONTRACT_ADDRESS, DEVCLUB.PVTKEY)

address = "0x689f98dbfec21d9a1229b4d08db66a694fafb166"
resp = devclub.mint_nft(address, unique_mint=True)
print(resp)

resp = devclub.get_balance(address)
print(resp)

resp = devclub.get_total_supply()
print(resp)

address = "0x91b8343CFb1A75a9B2Ecb69D49d60c86C97D55b5"
devclub.mint_nft(address, unique_mint=False)
